desc "Generate cicles's instances and question's instances"
task generate_cicles_questions: :environment do
  # CATEGORIES
  category_pre_inscription = Category.create!(name: 'Preinscripción')
  category_basic = Category.create!(name: 'Basico')
  category_family = Category.create!(name: 'Entorno Familiar')
  category_technology = Category.create!(name: 'Aspectos Tecnologicos')
  category_pregnancy = Category.create!(name: 'Aspectos del embarazo y nacimiento')
  category_development = Category.create!(name: 'Indicadores del desarrollo')
  category_home = Category.create!(name: 'En el hogar')
  category_study = Category.create!(name: 'Sobre el estudio')
  category_interests = Category.create!(name: 'Sus intereses')
  category_parents_vision = Category.create!(name: '¿Cómo ven los padres al niño?')
  category_feeding = Category.create!(name: 'Alimentación')
  category_sleep = Category.create!(name: 'Sueño')
  category_play = Category.create!(name: 'Juego')
  category_illness = Category.create!(name: 'Enfermedades')
  category_interconsulting = Category.create!(name: 'interconsultas')
  category_observation = Category.create!(name: 'Observaciones de importancia')
  category_education_project = Category.create!(name: 'Projecto Educativo')
  category_authorization_image = Category.create!(name: 'Autorización de imagen')

  # CYCLES
  pre_inscription = Cicle.create!(name: 'Pre Inscripción')
  maternal = Cicle.create!(name: 'Maternal')
  primary = Cicle.create!(name: 'Inicial/Primaria')
  secondary = Cicle.create!(name: 'Secundaria')

  # GRADES
  Grade.create!(name: 'Nivel 0', cicle: maternal)
  Grade.create!(name: 'Nivel 1', cicle: maternal)
  Grade.create!(name: 'Nivel 2', cicle: maternal)
  Grade.create!(name: 'Nivel 3', cicle: primary)
  Grade.create!(name: 'Nivel 4', cicle: primary)
  Grade.create!(name: 'Nivel 5', cicle: primary)
  Grade.create!(name: '1ero', cicle: primary)
  Grade.create!(name: '2do', cicle: primary)
  Grade.create!(name: '3ero', cicle: primary)
  Grade.create!(name: '4to', cicle: primary)
  Grade.create!(name: '5to', cicle: primary)
  Grade.create!(name: '6to', cicle: primary)
  Grade.create!(name: '1 CBU', cicle: secondary)
  Grade.create!(name: '2 CBU', cicle: secondary)
  Grade.create!(name: '3 CBU', cicle: secondary)

  # QUESTIONS

  # PREINSCRIPTION CYCLE
  pre_inscription.questions.create!(text: '¿Con quién/quiénes vive el alumno/a?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Tiene hermanos?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Concurren a nuestra Institución?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Ubicación del alumno/a a inscribir en el orden de los hermanos', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Cuántas laptops hay en la vivienda? (No incluir laptops de CEIBAL)', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Cuántas pc fijas hay en la vivienda?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Cuántas tablets hay en la vivienda? (No incluir tablets de CEIBAL)', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Cuántas laptop/tablet CEIBAL hay en la vivienda?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿En el hogar hay acceso a internet?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Tiene smartphone o celular inteligente con acceso a internet desde su hogar?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Asistió a Instituciones anteriores?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Desde qué edad asistió a otras Instituciones?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Nombre de instituciones anteriores:', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Escarlatina', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Sarampión', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Varicela', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Rubeola', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Paperas', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Tos convulsa', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Tuvo o tiene enfermedades importantes? ¿Cuáles?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Sufre enfermedades crónicas? ¿Cuáles?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Toma medicamentos regularmente? ¿Cuáles?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Existen consecuencias de accidentes? ¿Cuáles?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Alergias o intolerancia a algún alimento:', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Otra información que desee aclarar:', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Foniatra', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Psicomotricista', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Psicopedagogo', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Psicólogo', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Psiquiatra', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Neuropediatra', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Desea realizar algún comentario al respecto?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Cómo llegó a conocer nuestra Institución?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Qué conocimientos, habilidades y/o actitudes fundamentales cree que deben desarrollarse en el proceso de aprendizaje de su hijo/a para lograr un alto desempeño en la complejidad y desafíos del mu...', category: category_pre_inscription)
  pre_inscription.questions.create!(text: '¿Porque considera importante una propuesta bilingüe en la formación de su hijo/a?', category: category_pre_inscription)
  pre_inscription.questions.create!(text: 'Detalle aquí otra información que crea importante y que pueda contribuir a una atención eficiente e integral del alumno/a:', category: category_pre_inscription)

  # MATERNAL CYCLE
  maternal.questions.create!(text: '¿Con quién/quiénes vive el alumno/a?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Tiene hermanos?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Concurren a nuestra Institución?', category: category_pre_inscription)
  maternal.questions.create!(text: 'Ubicación del alumno/a a inscribir en el orden de los hermanos', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Cuántas laptops hay en la vivienda? (No incluir laptops de CEIBAL)', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Cuántas pc fijas hay en la vivienda?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Cuántas tablets hay en la vivienda? (No incluir tablets de CEIBAL)', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Cuántas laptop/tablet CEIBAL hay en la vivienda?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿En el hogar hay acceso a internet?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Tiene smartphone o celular inteligente con acceso a internet desde su hogar?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Asistió a Instituciones anteriores?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Desde qué edad asistió a otras Instituciones?', category: category_pre_inscription)
  maternal.questions.create!(text: 'Nombre de instituciones anteriores:', category: category_pre_inscription)
  maternal.questions.create!(text: 'Escarlatina', category: category_pre_inscription)
  maternal.questions.create!(text: 'Sarampión', category: category_pre_inscription)
  maternal.questions.create!(text: 'Varicela', category: category_pre_inscription)
  maternal.questions.create!(text: 'Rubeola', category: category_pre_inscription)
  maternal.questions.create!(text: 'Paperas', category: category_pre_inscription)
  maternal.questions.create!(text: 'Tos convulsa', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Tuvo o tiene enfermedades importantes? ¿Cuáles?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Sufre enfermedades crónicas? ¿Cuáles?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Toma medicamentos regularmente? ¿Cuáles?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Existen consecuencias de accidentes? ¿Cuáles?', category: category_pre_inscription)
  maternal.questions.create!(text: 'Alergias o intolerancia a algún alimento:', category: category_pre_inscription)
  maternal.questions.create!(text: 'Otra información que desee aclarar:', category: category_pre_inscription)
  maternal.questions.create!(text: 'Foniatra', category: category_pre_inscription)
  maternal.questions.create!(text: 'Psicomotricista', category: category_pre_inscription)
  maternal.questions.create!(text: 'Psicopedagogo', category: category_pre_inscription)
  maternal.questions.create!(text: 'Psicólogo', category: category_pre_inscription)
  maternal.questions.create!(text: 'Psiquiatra', category: category_pre_inscription)
  maternal.questions.create!(text: 'Neuropediatra', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Desea realizar algún comentario al respecto?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Cómo llegó a conocer nuestra Institución?', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Qué conocimientos, habilidades y/o actitudes fundamentales cree que deben desarrollarse en el proceso de aprendizaje de su hijo/a para lograr un alto desempeño en la complejidad y desafíos del mu...', category: category_pre_inscription)
  maternal.questions.create!(text: '¿Porque considera importante una propuesta bilingüe en la formación de su hijo/a?', category: category_pre_inscription)
  maternal.questions.create!(text: 'Detalle aquí otra información que crea importante y que pueda contribuir a una atención eficiente e integral del alumno/a:', category: category_pre_inscription)

  # BASIC
  maternal.questions.create!(text: 'Nombre completo:', category: category_basic)
  maternal.questions.create!(text: 'En casa lo llaman:', category: category_basic)
  maternal.questions.create!(text: 'Fecha de nacimiento:', category: category_basic)
  maternal.questions.create!(text: '¿Quiénes concurren a entrevista?', category: category_basic)
  maternal.questions.create!(text: '¿Asistió a instituciones anteriores?', category: category_basic)
  maternal.questions.create!(text: '¿Desde que edad?', category: category_basic)
  maternal.questions.create!(text: 'Nombre de instituciones anteriores', category: category_basic)
  maternal.questions.create!(text: '¿Lo cuida o cuidó una persona en casa que no sea mamá o papá? ', category: category_basic)

  # FAMILY
  maternal.questions.create!(text: '¿Con quién vive el alumno/a?', category: category_family)
  maternal.questions.create!(text: '¿Tiene hermanos?', category: category_family)
  maternal.questions.create!(text: '¿Los hermanos concurren a nuestra institución?', category: category_family)
  maternal.questions.create!(text: '¿Ubicación del alumno/a en el orden de hermanos?', category: category_family)
  maternal.questions.create!(text: 'Hermanos (Edades y Sexo):', category: category_family)
  maternal.questions.create!(text: '¿En caso de separación: qué edad tenía el alumno y como lo transitó?', category: category_family)
  maternal.questions.create!(text: 'En caso de hermanos/as, ¿cómo es el vínculo con ellos/as?', category: category_family)
  maternal.questions.create!(text: '¿Tiene vínculos con tíos,  primos, abuelos?', category: category_family)
  maternal.questions.create!(text: 'Hecho o situación familiar que amerite informar', category: category_family)

  # TECHNOLOGY
  maternal.questions.create!(text: '¿Cuántas laptops hay en la vivienda? (No incluir ceibal)', category: category_technology)
  maternal.questions.create!(text: '¿Cuántas pc fijas hay en la vivienda?', category: category_technology)
  maternal.questions.create!(text: '¿Cuántas tablets hay en la vivienda? (No incluir ceibal)', category: category_technology)
  maternal.questions.create!(text: '¿Cuántas laptop/tablets CEIBAL hay en la vivienda?', category: category_technology)
  maternal.questions.create!(text: '¿En el hogar hay acceso a internet?', category: category_technology)
  maternal.questions.create!(text: '¿Tiene smartphone o celular inteligente con acceso a internet desde su hogar?', category: category_technology)

  # PREGNANCY
  maternal.questions.create!(text: '¿Cómo fue el embarazo? ¿Tuvieron que hacer tratamiento?', category: category_pregnancy)
  maternal.questions.create!(text: '¿Cómo vivieron el momento del nacimiento?', category: category_pregnancy)
  maternal.questions.create!(text: '¿Fue un nacimiento a término? En caso negativo, ¿de cuántas semanas?', category: category_pregnancy)
  maternal.questions.create!(text: '¿Fue parto vaginal o césarea?', category: category_pregnancy)
  maternal.questions.create!(text: '¿Hubo alguna complicación al nacer?', category: category_pregnancy)
  maternal.questions.create!(text: 'En caso de adopción, ¿cómo vivieron el proceso?', category: category_pregnancy)

  # DEVELOPMENT
  maternal.questions.create!(text: '¿Gatea? ¿Desde cuándo?', category: category_development)
  maternal.questions.create!(text: '¿Marcha? ¿Desde cuándo?', category: category_development)
  maternal.questions.create!(text: '¿Vocaliza o balbucea? ¿Desde cuándo?', category: category_development)
  maternal.questions.create!(text: 'Si se equivoca al hablar, ¿Es corregido? ¿Cómo?', category: category_development)

  # PARENTS VISION
  maternal.questions.create!(text: '¿Comunica lo que siente?', category: category_parents_vision)
  maternal.questions.create!(text: '¿Hace rabietas? ¿Qué lo enoja?', category: category_parents_vision)
  maternal.questions.create!(text: '¿Hay puesta de límites? En caso de afirmativo, ¿cómo lo manejan, estrategias que usan?', category: category_parents_vision)
  maternal.questions.create!(text: '¿Le tiene miedo a algo?', category: category_parents_vision)
  maternal.questions.create!(text: '¿Uso de pantallas? ¿Cuántas horas? ¿qué mira?', category: category_parents_vision)

  # FEEDING
  maternal.questions.create!(text: 'Los primeros tiempos fue ¿lactancia exclusiva?', category: category_feeding)
  maternal.questions.create!(text: 'Si dejó el pecho, ¿cuándo lo hizo?', category: category_feeding)
  maternal.questions.create!(text: '¿Tomó/toma mamadera?', category: category_feeding)
  maternal.questions.create!(text: '¿Usó o usa chupete?', category: category_feeding)
  maternal.questions.create!(text: 'Alimentación sólida: ¿Qué preferencia tiene? ¿horarios de la comida?', category: category_feeding)
  maternal.questions.create!(text: '¿Quién le da de comer?', category: category_feeding)
  maternal.questions.create!(text: 'En caso de comer solo, ¿usa utensilios? ¿Come con la mano?', category: category_feeding)

  # SLEEP
  maternal.questions.create!(text: '¿Cómo concilia el sueño? ¿Solo? ¿Lo hamacan? ¿En el coche? ¿colecho?', category: category_sleep)
  maternal.questions.create!(text: '¿Duerme solo?', category: category_sleep)

  # PLAY
  maternal.questions.create!(text: '¿A qué juega? ¿con quién juega? ', category: category_play)
  maternal.questions.create!(text: '¿Le leen cuentos?', category: category_play)
  maternal.questions.create!(text: '¿Le cantan? ¿Cuándo?', category: category_play)
  maternal.questions.create!(text: '¿Tiene algún objeto de apego?', category: category_play)
  maternal.questions.create!(text: '¿Qué lugares frecuenta/conoce? (plaza, casa de algún familiar/playa/patio/campo, etc.)', category: category_play)

  # ILLNESS
  maternal.questions.create!(text: 'Escarlatina', category: category_illness)
  maternal.questions.create!(text: 'Sarampión', category: category_illness)
  maternal.questions.create!(text: 'Varicela', category: category_illness)
  maternal.questions.create!(text: 'Rubeola', category: category_illness)
  maternal.questions.create!(text: 'Paperas', category: category_illness)
  maternal.questions.create!(text: 'Tos convulsa', category: category_illness)
  maternal.questions.create!(text: '¿Tuvo o tiene enfermedades importantes? ¿Cuáles?', category: category_illness)
  maternal.questions.create!(text: '¿Sufre enfermedades crónicas? ¿Cuáles?', category: category_illness)
  maternal.questions.create!(text: '¿Toma medicamentos regularmente? ¿Cuáles?', category: category_illness)
  maternal.questions.create!(text: '¿Existen consecuencias de accidentes? ¿Cuáles?', category: category_illness)
  maternal.questions.create!(text: 'Alergias o intolerancia a algún alimento:', category: category_illness)
  maternal.questions.create!(text: 'Otra información importante:', category: category_illness)
  maternal.questions.create!(text: 'Comentarios Director', category: category_illness)

  # INTERCONSULTING
  maternal.questions.create!(text: 'Foniatra', category: category_interconsulting)
  maternal.questions.create!(text: 'Psicomotricista', category: category_interconsulting)
  maternal.questions.create!(text: 'Psicopedagogo', category: category_interconsulting)
  maternal.questions.create!(text: 'Psicólogo', category: category_interconsulting)
  maternal.questions.create!(text: 'Psiquiatra', category: category_interconsulting)
  maternal.questions.create!(text: 'Neuropediatra', category: category_interconsulting)
  maternal.questions.create!(text: '¿Desea realizar algún comentario al respecto?', category: category_interconsulting)
  maternal.questions.create!(text: 'Comentarios Director', category: category_interconsulting)
  maternal.questions.create!(text: 'Adjuntar informes', category: category_interconsulting)

  # OBSERVATIONS
  maternal.questions.create!(text: 'Respecto a los cuidados diarios ¿quién se ocupa de qué? ¿baño? ¿sueño?', category: category_observation)
  maternal.questions.create!(text: 'Relación con otros miembros de la familia', category: category_observation)
  maternal.questions.create!(text: 'Preocupaciones entorno a la crianza y el desarrollo de su hijo/a', category: category_observation)
  maternal.questions.create!(text: 'Aspectos importantes que debemos considerar', category: category_observation)
  maternal.questions.create!(text: 'Lenguaje y comunicación', category: category_observation)
  maternal.questions.create!(text: '¿Cómo define a su hijo? Mi hijo/a es...', category: category_observation)

  # EDUCATION PROJECT
  maternal.questions.create!(text: '¿Cómo llegó a conocer nuestra institución?', category: category_education_project)
  maternal.questions.create!(text: '¿Qué conocimientos, habilidades y/o actitudes fundamentales cree que deben desarrollarse en el proceso de aprendizaje de su hijo/a para lograr un  alto desempeño en la complejidad y desafíos del mundo actual?', category: category_education_project)
  maternal.questions.create!(text: '¿Por qué considera importante una propuesta bilingüe en la formación de su hijo/a?', category: category_education_project)
  maternal.questions.create!(text: 'Detalle aquí otra información que crea importante y que pueda contribuir a una atención eficiente e integral del alumno/a:', category: category_education_project)
  maternal.questions.create!(text: '¿Qué expectativa pedagógica, vincular, etc, tiene la familia respecto a la Institución Educativa?', category: category_education_project)

  # IMAGE AUTHORIZATION
  maternal.questions.create!(text: '¿Autoriza imagen?', category: category_authorization_image)
  maternal.questions.create!(text: 'Adjuntar documento firmado', category: category_authorization_image)

  # PRIMARY CYCLE

  # PREINSCRIPTION
  primary.questions.create!(text: '¿Con quién/quiénes vive el alumno/a?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Tiene hermanos?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Concurren a nuestra Institución?', category: category_pre_inscription)
  primary.questions.create!(text: 'Ubicación del alumno/a a inscribir en el orden de los hermanos', category: category_pre_inscription)
  primary.questions.create!(text: '¿Cuántas laptops hay en la vivienda? (No incluir laptops de CEIBAL)', category: category_pre_inscription)
  primary.questions.create!(text: '¿Cuántas pc fijas hay en la vivienda?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Cuántas tablets hay en la vivienda? (No incluir tablets de CEIBAL)', category: category_pre_inscription)
  primary.questions.create!(text: '¿Cuántas laptop/tablet CEIBAL hay en la vivienda?', category: category_pre_inscription)
  primary.questions.create!(text: '¿En el hogar hay acceso a internet?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Tiene smartphone o celular inteligente con acceso a internet desde su hogar?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Asistió a Instituciones anteriores?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Desde qué edad asistió a otras Instituciones?', category: category_pre_inscription)
  primary.questions.create!(text: 'Nombre de instituciones anteriores:', category: category_pre_inscription)
  primary.questions.create!(text: 'Escarlatina', category: category_pre_inscription)
  primary.questions.create!(text: 'Sarampión', category: category_pre_inscription)
  primary.questions.create!(text: 'Varicela', category: category_pre_inscription)
  primary.questions.create!(text: 'Rubeola', category: category_pre_inscription)
  primary.questions.create!(text: 'Paperas', category: category_pre_inscription)
  primary.questions.create!(text: 'Tos convulsa', category: category_pre_inscription)
  primary.questions.create!(text: '¿Tuvo o tiene enfermedades importantes? ¿Cuáles?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Sufre enfermedades crónicas? ¿Cuáles?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Toma medicamentos regularmente? ¿Cuáles?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Existen consecuencias de accidentes? ¿Cuáles?', category: category_pre_inscription)
  primary.questions.create!(text: 'Alergias o intolerancia a algún alimento:', category: category_pre_inscription)
  primary.questions.create!(text: 'Otra información que desee aclarar:', category: category_pre_inscription)
  primary.questions.create!(text: 'Foniatra', category: category_pre_inscription)
  primary.questions.create!(text: 'Psicomotricista', category: category_pre_inscription)
  primary.questions.create!(text: 'Psicopedagogo', category: category_pre_inscription)
  primary.questions.create!(text: 'Psicólogo', category: category_pre_inscription)
  primary.questions.create!(text: 'Psiquiatra', category: category_pre_inscription)
  primary.questions.create!(text: 'Neuropediatra', category: category_pre_inscription)
  primary.questions.create!(text: '¿Desea realizar algún comentario al respecto?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Cómo llegó a conocer nuestra Institución?', category: category_pre_inscription)
  primary.questions.create!(text: '¿Qué conocimientos, habilidades y/o actitudes fundamentales cree que deben desarrollarse en el proceso de aprendizaje de su hijo/a para lograr un alto desempeño en la complejidad y desafíos del mu...', category: category_pre_inscription)
  primary.questions.create!(text: '¿Porque considera importante una propuesta bilingüe en la formación de su hijo/a?', category: category_pre_inscription)
  primary.questions.create!(text: 'Detalle aquí otra información que crea importante y que pueda contribuir a una atención eficiente e integral del alumno/a:', category: category_pre_inscription)

  # BASIC
  primary.questions.create!(text: 'Nombre completo:', category: category_basic)
  primary.questions.create!(text: 'En casa lo llaman:', category: category_basic)
  primary.questions.create!(text: 'Fecha de nacimiento:', category: category_basic)
  primary.questions.create!(text: '¿Quiénes concurren a entrevista?', category: category_basic)
  primary.questions.create!(text: '¿Asistió a instituciones anteriores?', category: category_basic)
  primary.questions.create!(text: '¿Desde que edad?', category: category_basic)
  primary.questions.create!(text: 'Nombre de instituciones anteriores', category: category_basic)
  primary.questions.create!(text: 'Escolaridad/Comentarios Director', category: category_basic)

  # FAMILY
  primary.questions.create!(text: '¿Con quién vive el alumno/a?', category: category_family)
  primary.questions.create!(text: '¿Tiene hermanos?', category: category_family)
  primary.questions.create!(text: '¿Los hermanos concurren a nuestra institución?', category: category_family)
  primary.questions.create!(text: '¿Ubicación del alumno/a en el orden de hermanos?', category: category_family)
  primary.questions.create!(text: 'Hermanos (Edades y Sexo):', category: category_family)
  primary.questions.create!(text: '¿En caso de separación: qué edad tenía el alumno y como lo transitó?', category: category_family)
  primary.questions.create!(text: 'En caso de hermanos/as, ¿cómo es el vínculo con ellos/as?', category: category_family)
  primary.questions.create!(text: '¿Tiene vínculos con tíos,  primos, abuelos?', category: category_family)
  primary.questions.create!(text: 'Hecho o situación familiar que amerite informar', category: category_family)

  # TECHNOLOGY
  primary.questions.create!(text: '¿Cuántas laptops hay en la vivienda? (No incluir ceibal)', category: category_technology)
  primary.questions.create!(text: '¿Cuántas pc fijas hay en la vivienda?', category: category_technology)
  primary.questions.create!(text: '¿Cuántas tablets hay en la vivienda? (No incluir ceibal)', category: category_technology)
  primary.questions.create!(text: '¿Cuántas laptop/tablets CEIBAL hay en la vivienda?', category: category_technology)
  primary.questions.create!(text: '¿En el hogar hay acceso a internet?', category: category_technology)
  primary.questions.create!(text: '¿Tiene smartphone o celular inteligente con acceso a internet desde su hogar?', category: category_technology)

  # PREGNANCY
  primary.questions.create!(text: '¿Cómo fue el embarazo? ¿Tuvieron que hacer tratamiento?', category: category_pregnancy)
  primary.questions.create!(text: '¿Cómo vivieron el momento del nacimiento?', category: category_pregnancy)
  primary.questions.create!(text: '¿Fue un nacimiento a término? En caso negativo, ¿de cuántas semanas?', category: category_pregnancy)
  primary.questions.create!(text: '¿Fue parto vaginal o césarea?', category: category_pregnancy)
  primary.questions.create!(text: '¿Hubo alguna complicación al nacer?', category: category_pregnancy)
  primary.questions.create!(text: 'En caso de adopción, ¿cómo vivieron el proceso?', category: category_pregnancy)

  # PARENTS VISION
  primary.questions.create!(text: '¿Hace rabietas? ¿Qué lo enoja?', category: category_parents_vision)
  primary.questions.create!(text: '¿Hay puesta de límites? En caso de afirmativo, ¿cómo lo manejan, estrategias que usan?', category: category_parents_vision)
  primary.questions.create!(text: '¿Le tiene miedo a algo?', category: category_parents_vision)
  primary.questions.create!(text: '¿Uso de pantallas? ¿cuántas horas? ¿qué mira?', category: category_parents_vision)
  primary.questions.create!(text: '¿Comunica lo que siente?', category: category_parents_vision)
  primary.questions.create!(text: 'Cómo negocian los NO en el hogar?', category: category_parents_vision)

  # FEEDING
  primary.questions.create!(text: 'Alimentación sólida: ¿Qué preferencia tiene? ¿horarios de la comida?', category: category_feeding)

  # SLEEP
  primary.questions.create!(text: '¿Cómo concilia el sueño? ¿Solo? ¿Lo hamacan? ¿En el coche? ¿colecho?', category: category_sleep)
  primary.questions.create!(text: '¿Duerme solo?', category: category_sleep)
  primary.questions.create!(text: '¿Duerme siestas?', category: category_sleep)

  # PLAY
  primary.questions.create!(text: '¿A qué juega? ¿con quién juega? ', category: category_play)

  # ILLNESS
  primary.questions.create!(text: 'Escarlatina', category: category_illness)
  primary.questions.create!(text: 'Sarampión', category: category_illness)
  primary.questions.create!(text: 'Varicela', category: category_illness)
  primary.questions.create!(text: 'Rubeola', category: category_illness)
  primary.questions.create!(text: 'Paperas', category: category_illness)
  primary.questions.create!(text: 'Tos convulsa', category: category_illness)
  primary.questions.create!(text: '¿Tuvo o tiene enfermedades importantes? ¿Cuáles?', category: category_illness)
  primary.questions.create!(text: '¿Sufre enfermedades crónicas? ¿Cuáles?', category: category_illness)
  primary.questions.create!(text: '¿Toma medicamentos regularmente? ¿Cuáles?', category: category_illness)
  primary.questions.create!(text: '¿Existen consecuencias de accidentes? ¿Cuáles?', category: category_illness)
  primary.questions.create!(text: 'Alergias o intolerancia a algún alimento:', category: category_illness)
  primary.questions.create!(text: 'Otra información importante:', category: category_illness)
  primary.questions.create!(text: 'Comentarios Director', category: category_illness)

  # INTERCONSULTING
  primary.questions.create!(text: 'Foniatra', category: category_interconsulting)
  primary.questions.create!(text: 'Psicomotricista', category: category_interconsulting)
  primary.questions.create!(text: 'Psicopedagogo', category: category_interconsulting)
  primary.questions.create!(text: 'Psicólogo', category: category_interconsulting)
  primary.questions.create!(text: 'Psiquiatra', category: category_interconsulting)
  primary.questions.create!(text: 'Neuropediatra', category: category_interconsulting)
  primary.questions.create!(text: '¿Desea realizar algún comentario al respecto?', category: category_interconsulting)
  primary.questions.create!(text: 'Comentarios Director', category: category_interconsulting)
  primary.questions.create!(text: 'Adjuntar informes', category: category_interconsulting)

  # OBSERVATIONS
  primary.questions.create!(text: 'Preocupaciones entorno a la crianza y el desarrollo de su hijo/a', category: category_observation)
  primary.questions.create!(text: 'Aspectos importantes que debemos considerar', category: category_observation)
  primary.questions.create!(text: 'Lenguaje y comunicación', category: category_observation)
  primary.questions.create!(text: '¿Cómo define a su hijo? Mi hijo/a es...', category: category_observation)

  # EDUCATION PROJECT
  primary.questions.create!(text: '¿Cómo llegó a conocer nuestra institución?', category: category_education_project)
  primary.questions.create!(text: '¿Qué conocimientos, habilidades y/o actitudes fundamentales cree que deben desarrollarse en el proceso de aprendizaje de su hijo/a para lograr un  alto desempeño en la complejidad y desafíos del mundo actual?', category: category_education_project)
  primary.questions.create!(text: '¿Por qué considera importante una propuesta bilingüe en la formación de su hijo/a?', category: category_education_project)
  primary.questions.create!(text: 'Detalle aquí otra información que crea importante y que pueda contribuir a una atención eficiente e integral del alumno/a:', category: category_education_project)
  primary.questions.create!(text: '¿Qué expectativa pedagógica, vincular, etc, tiene la familia respecto a la Institución Educativa?', category: category_education_project)
  primary.questions.create!(text: '¿Qué no puede faltar en el vínculo con la Institución?', category: category_education_project)
  primary.questions.create!(text: '¿Qué opina de los grupos de WhatsApp de padres?', category: category_education_project)

  # IMAGE AUTHORIZATION
  primary.questions.create!(text: '¿Autoriza imagen?', category: category_authorization_image)
  primary.questions.create!(text: 'Adjuntar documento firmado', category: category_authorization_image)

  # SECONDARY CYCLE

  # PREINSCRIPTION
  secondary.questions.create!(text: '¿Con quién/quiénes vive el alumno/a?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Tiene hermanos?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Concurren a nuestra Institución?', category: category_pre_inscription)
  secondary.questions.create!(text: 'Ubicación del alumno/a a inscribir en el orden de los hermanos', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Cuántas laptops hay en la vivienda? (No incluir laptops de CEIBAL)', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Cuántas pc fijas hay en la vivienda?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Cuántas tablets hay en la vivienda? (No incluir tablets de CEIBAL)', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Cuántas laptop/tablet CEIBAL hay en la vivienda?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿En el hogar hay acceso a internet?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Tiene smartphone o celular inteligente con acceso a internet desde su hogar?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Asistió a Instituciones anteriores?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Desde qué edad asistió a otras Instituciones?', category: category_pre_inscription)
  secondary.questions.create!(text: 'Nombre de instituciones anteriores:', category: category_pre_inscription)
  secondary.questions.create!(text: 'Escarlatina', category: category_pre_inscription)
  secondary.questions.create!(text: 'Sarampión', category: category_pre_inscription)
  secondary.questions.create!(text: 'Varicela', category: category_pre_inscription)
  secondary.questions.create!(text: 'Rubeola', category: category_pre_inscription)
  secondary.questions.create!(text: 'Paperas', category: category_pre_inscription)
  secondary.questions.create!(text: 'Tos convulsa', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Tuvo o tiene enfermedades importantes? ¿Cuáles?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Sufre enfermedades crónicas? ¿Cuáles?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Toma medicamentos regularmente? ¿Cuáles?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Existen consecuencias de accidentes? ¿Cuáles?', category: category_pre_inscription)
  secondary.questions.create!(text: 'Alergias o intolerancia a algún alimento:', category: category_pre_inscription)
  secondary.questions.create!(text: 'Otra información que desee aclarar:', category: category_pre_inscription)
  secondary.questions.create!(text: 'Foniatra', category: category_pre_inscription)
  secondary.questions.create!(text: 'Psicomotricista', category: category_pre_inscription)
  secondary.questions.create!(text: 'Psicopedagogo', category: category_pre_inscription)
  secondary.questions.create!(text: 'Psicólogo', category: category_pre_inscription)
  secondary.questions.create!(text: 'Psiquiatra', category: category_pre_inscription)
  secondary.questions.create!(text: 'Neuropediatra', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Desea realizar algún comentario al respecto?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Cómo llegó a conocer nuestra Institución?', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Qué conocimientos, habilidades y/o actitudes fundamentales cree que deben desarrollarse en el proceso de aprendizaje de su hijo/a para lograr un alto desempeño en la complejidad y desafíos del mu...', category: category_pre_inscription)
  secondary.questions.create!(text: '¿Porque considera importante una propuesta bilingüe en la formación de su hijo/a?', category: category_pre_inscription)
  secondary.questions.create!(text: 'Detalle aquí otra información que crea importante y que pueda contribuir a una atención eficiente e integral del alumno/a:', category: category_pre_inscription)

  # BASIC
  secondary.questions.create!(text: 'Nombre completo:', category: category_basic)
  secondary.questions.create!(text: 'En casa lo llaman:', category: category_basic)
  secondary.questions.create!(text: 'Fecha de nacimiento:', category: category_basic)
  secondary.questions.create!(text: '¿Quiénes concurren a entrevista?', category: category_basic)
  secondary.questions.create!(text: '¿Asistió a instituciones anteriores?', category: category_basic)
  secondary.questions.create!(text: '¿Desde que edad?', category: category_basic)
  secondary.questions.create!(text: 'Nombre de instituciones anteriores', category: category_basic)
  secondary.questions.create!(text: '¿Se realizó test o diagnóstico?', category: category_basic)
  secondary.questions.create!(text: 'Escolaridad/Comentarios Director', category: category_basic)

  # FAMILY
  secondary.questions.create!(text: '¿Con quién vive el alumno/a?', category: category_family)
  secondary.questions.create!(text: '¿Tiene hermanos?', category: category_family)
  secondary.questions.create!(text: '¿Los hermanos concurren a nuestra institución?', category: category_family)
  secondary.questions.create!(text: '¿Ubicación del alumno/a en el orden de hermanos?', category: category_family)
  secondary.questions.create!(text: 'Hermanos (Edades y Sexo):', category: category_family)
  secondary.questions.create!(text: '¿En caso de separación: qué edad tenía el alumno y como lo transitó?', category: category_family)
  secondary.questions.create!(text: 'En caso de hermanos/as, ¿cómo es el vínculo con ellos/as?', category: category_family)
  secondary.questions.create!(text: '¿Tiene vínculos con tíos,  primos, abuelos?', category: category_family)
  secondary.questions.create!(text: 'Hecho o situación familiar que amerite informar', category: category_family)

  # TECHNOLOGY
  secondary.questions.create!(text: '¿Cuántas laptops hay en la vivienda? (No incluir ceibal)', category: category_technology)
  secondary.questions.create!(text: '¿Cuántas pc fijas hay en la vivienda?', category: category_technology)
  secondary.questions.create!(text: '¿Cuántas tablets hay en la vivienda? (No incluir ceibal)', category: category_technology)
  secondary.questions.create!(text: '¿Cuántas laptop/tablets CEIBAL hay en la vivienda?', category: category_technology)
  secondary.questions.create!(text: '¿En el hogar hay acceso a internet?', category: category_technology)
  secondary.questions.create!(text: '¿Tiene smartphone o celular inteligente con acceso a internet desde su hogar?', category: category_technology)

  # PREGNANCY
  secondary.questions.create!(text: '¿Cómo fue el embarazo? ¿Tuvieron que hacer tratamiento?', category: category_pregnancy)
  secondary.questions.create!(text: '¿Cómo vivieron el momento del nacimiento?', category: category_pregnancy)
  secondary.questions.create!(text: '¿Fue un nacimiento a término? En caso negativo, ¿de cuántas semanas?', category: category_pregnancy)
  secondary.questions.create!(text: '¿Fue parto vaginal o césarea?', category: category_pregnancy)
  secondary.questions.create!(text: '¿Hubo alguna complicación al nacer?', category: category_pregnancy)
  secondary.questions.create!(text: 'En caso de adopción, ¿cómo vivieron el proceso?', category: category_pregnancy)

  # HOME
  secondary.questions.create!(text: '¿Colabora en tareas de la casa?', category: category_home)
  secondary.questions.create!(text: '¿Con qué integrante de la flia estás más horas?', category: category_home)
  secondary.questions.create!(text: '¿Con quien conversas de tus problemas?', category: category_home)
  secondary.questions.create!(text: '¿Qué haces en tu tiempo libre?', category: category_home)

  # STUDY
  secondary.questions.create!(text: '¿Necesitas apoyo o lo haces en forma independiente?', category: category_home)
  secondary.questions.create!(text: '¿Has estudiado en grupo o siempre solo?', category: category_home)
  secondary.questions.create!(text: '¿Tienes alguna dificultad en algún área?', category: category_home)
  secondary.questions.create!(text: '¿Te distraes con facilidad o te puedes concentrar por un largo período?', category: category_home)
  secondary.questions.create!(text: '¿Sabes el motivo de esta?', category: category_home)
  secondary.questions.create!(text: '¿Dispones de textos, materiales, P.C, etc?', category: category_home)
  secondary.questions.create!(text: '¿Cómo organizas el tiempo para las tareas domiciliarias?', category: category_home)
  secondary.questions.create!(text: '¿Quieres agregar algo que a tu juicio favorezca o dificulte tu aprendizaje?', category: category_home)

  # INTERESTS
  secondary.questions.create!(text: '¿A qué lugares de reunión concurres habitualmente?', category: category_home)
  secondary.questions.create!(text: '¿Tienes amigos? ¿De dónde son?', category: category_home)
  secondary.questions.create!(text: '¿Practicas algún deporte, idioma, actividad musical, etc.? ¿Dónde?', category: category_home)
  secondary.questions.create!(text: 'En tu tiempo libre: ¿Miras T,V.? ¿Escuchas radio?¿Lees?¿Chateas?', category: category_home)
  secondary.questions.create!(text: '¿A partir de qué hora te encuentras en casa con tu familia?', category: category_home)
  secondary.questions.create!(text: '¿En qué actividades has obtenido la mayor satisfacción?', category: category_home)
  secondary.questions.create!(text: '¿En qué actividades te has sentido derrotado?', category: category_home)
  secondary.questions.create!(text: '¿Tienes alguna preocupación actual?', category: category_home)
  secondary.questions.create!(text: '¿Qué cosas te hacen enojar?', category: category_home)
  secondary.questions.create!(text: '¿Qué cosas te ponen contento?', category: category_home)
  secondary.questions.create!(text: '¿Tienes facilidad para relacionarte con los chicos?', category: category_home)
  secondary.questions.create!(text: '¿Y con los adultos?', category: category_home)
  secondary.questions.create!(text: 'Propone alguna actividad que  consideres que no puede faltar en el liceo', category: category_home)

  # ILLNESS
  secondary.questions.create!(text: 'Escarlatina', category: category_illness)
  secondary.questions.create!(text: 'Sarampión', category: category_illness)
  secondary.questions.create!(text: 'Varicela', category: category_illness)
  secondary.questions.create!(text: 'Rubeola', category: category_illness)
  secondary.questions.create!(text: 'Paperas', category: category_illness)
  secondary.questions.create!(text: 'Tos convulsa', category: category_illness)
  secondary.questions.create!(text: '¿Tuvo o tiene enfermedades importantes? ¿Cuáles?', category: category_illness)
  secondary.questions.create!(text: '¿Sufre enfermedades crónicas? ¿Cuáles?', category: category_illness)
  secondary.questions.create!(text: '¿Toma medicamentos regularmente? ¿Cuáles?', category: category_illness)
  secondary.questions.create!(text: '¿Existen consecuencias de accidentes? ¿Cuáles?', category: category_illness)
  secondary.questions.create!(text: 'Alergias o intolerancia a algún alimento:', category: category_illness)
  secondary.questions.create!(text: 'Otra información importante:', category: category_illness)
  secondary.questions.create!(text: 'Comentarios Director', category: category_illness)

  # INTERCONSULTING
  secondary.questions.create!(text: 'Foniatra', category: category_interconsulting)
  secondary.questions.create!(text: 'Psicomotricista', category: category_interconsulting)
  secondary.questions.create!(text: 'Psicopedagogo', category: category_interconsulting)
  secondary.questions.create!(text: 'Psicólogo', category: category_interconsulting)
  secondary.questions.create!(text: 'Psiquiatra', category: category_interconsulting)
  secondary.questions.create!(text: 'Neuropediatra', category: category_interconsulting)
  secondary.questions.create!(text: '¿Desea realizar algún comentario al respecto?', category: category_interconsulting)
  secondary.questions.create!(text: 'Comentarios Director', category: category_interconsulting)
  secondary.questions.create!(text: 'Adjuntar informes', category: category_interconsulting)

  # OBSERVATION
  secondary.questions.create!(text: 'Preocupaciones entorno a la crianza y el desarrollo de su hijo/a', category: category_observation)
  secondary.questions.create!(text: 'Aspectos importantes que debemos considerar', category: category_observation)
  secondary.questions.create!(text: 'Lenguaje y comunicación', category: category_observation)
  secondary.questions.create!(text: '¿Qué le gusta hacer?', category: category_observation)
  secondary.questions.create!(text: '¿Qué talento presenta?', category: category_observation)
  secondary.questions.create!(text: '¿Cómo define a su hijo? Mi hijo/a es...', category: category_observation)

  # EDUCATION PROJECT
  secondary.questions.create!(text: '¿Cómo llegó a conocer nuestra institución?', category: category_education_project)
  secondary.questions.create!(text: '¿Qué conocimientos, habilidades y/o actitudes fundamentales cree que deben desarrollarse en el proceso de aprendizaje de su hijo/a para lograr un  alto desempeño en la complejidad y desafíos del mundo actual?', category: category_education_project)
  secondary.questions.create!(text: '¿Por qué considera importante una propuesta bilingüe en la formación de su hijo/a?', category: category_education_project)
  secondary.questions.create!(text: 'Detalle aquí otra información que crea importante y que pueda contribuir a una atención eficiente e integral del alumno/a:', category: category_education_project)
  secondary.questions.create!(text: '¿Qué expectativa pedagógica, vincular, etc, tiene la familia respecto a la Institución Educativa?', category: category_education_project)
  secondary.questions.create!(text: '¿Qué expectativa pedagógica, vincular, etc, tiene la familia respecto a la Institución Educativa?', category: category_education_project)

  # IMAGE AUTHORIZATION
  secondary.questions.create!(text: '¿Autoriza imagen?', category: category_authorization_image)
  secondary.questions.create!(text: 'Adjuntar documento firmado', category: category_authorization_image)
end
